name: autoformat-json

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - '**.json'

jobs:
  autoformat-files:
    name: Autoformat JSON files
    runs-on: ubuntu-latest
    if:  ${{ !github.event.pull_request.draft }} 
    
    steps:     
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }} 

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get commits list from branch
        run: |
          #!/bin/bash 
          git log --no-merges --name-only --format="" origin/${{ github.event.pull_request.head.ref }} --not origin/${{ github.event.repository.default_branch }} > ./commits.txt

          sort ./commits.txt | uniq
          sort ./commits.txt | uniq > ./file.txt
          rm ./commits.txt      

      - name: Autoformat JSON files
        run: |
          #!/bin/bash               
          echo "Reformatting JSON files .."

          while read line; do 
          if [[ $line == *.json ]]; then 
              filename="./$line"
              if test -f "$filename"; then
                  echo "analyzing JSON file $filename .."
                  echo "" >> ./run_results.txt
                  echo "***analyzing file***" >> ./run_results.txt
                  echo $filename >> ./run_results.txt              
                  ./.github/actions/json_formatter.py --file $filename >> ./run_results.txt 
                  echo "---------------------------------------------------" >> ./run_results.txt
              fi  
          fi done < ./file.txt
    
          if test -f ./run_results.txt; then
              if grep -i "error:" ./run_results.txt; then
                  echo "***************************************************"
                  echo "ERROR(-s) OCCURED DURING FORMATTING OF THE FILE(-s), FETCHING LOG FILE:"
                  cat ./run_results.txt
                  echo ""
                  echo "***************************************************"
                  echo "*** All changes from this run won't be committed ***"
                  exit 99
              else
                  echo "JSON files formatted sucessfully"
              fi
              rm ./run_results.txt
          fi
           
          rm ./file.txt           

      - name: Commit files
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git commit --all -m"Reformat JSON Files to common format." || true
      - name: Push
        # For on-action == pull request -> "HEAD:${GITHUB_HEAD_REF}", for == push -> "HEAD" 
        run: git push "https://${{github.actor}}:${{secrets.SOURCE_PUSH_TOKEN}}@${GITHUB_SERVER_URL##*/}/${{github.repository}}.git" "HEAD:${GITHUB_HEAD_REF}"